#!/bin/csh -f
source /apps/intel/compilers_and_libraries_2020/linux/bin/compilervars.csh intel64
setenv NWCHEM_TOP /home/ondra_d/CODE/nwchem/
cd $NWCHEM_TOP/src
setenv NWCHEM_TARGET LINUX64
setenv NWCHEM_MODULES 'all'
setenv CCSDTQ yes
setenv BLASOPT '-I/apps/intel/compilers_and_libraries_2020.4.304/linux/mkl/include -L/apps/intel/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64_lin -Wl,--start-group -lmkl_sequential -lmkl_intel_lp64 -lmkl_core -Wl,--end-group -lpthread'
setenv LAPACK_LIB  -lmkl_lapack95_ilp64
setenv  MPI_INCLUDE /apps/openmpi/openmpi-4.1.1/src/openmpi-4.1.1-x86_64-intel_19.1.3/ompi/include
setenv MPI_LIB '/apps/openmpi/openmpi-4.1.1/src/openmpi-4.1.1-x86_64-intel_19.1.3/ompi/.libs'
setenv USE_MPI yes
setenv OPENMPI /apps/openmpi/openmpi-4.1.1/arch/x86_64-intel_19.1.3
setenv PATH ${PATH}:${OPENMPI}/bin
setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${OPENMPI}/lib
setenv HAS_BLAS yes
setenv CC icc
setenv FC ifort
setenv BLAS_SIZE 8
make
